# Generated by Django 5.2.8 on 2025-12-03 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_creativeprofile_profile_image_userinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_text', models.TextField(help_text='The legal text of the agreement.')),
                ('is_client_signed', models.BooleanField(default=False)),
                ('client_signed_at', models.DateTimeField(blank=True, null=True)),
                ('is_creative_signed', models.BooleanField(default=False)),
                ('creative_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='core.booking')),
            ],
        ),
    ]
