# Generated by Django 5.2.7 on 2025-12-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chatmessage_emailotp_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.booking'),
        ),
    ]
